### ISSUE TITLE
Problème d'envoi d'emails

### ISSUE THREAD

**Issue by sbisbilo** [Tontonjo/proxmox_toolbox#1]
Bonjour, merci pour ce script fort utile et bien réalisé :)
J'ai tout de même un problème avec la configuration des notifications emails voici le log :

Jul 26 15:30:01 pve postfix/smtp[4074964]: 92D543404C5: to=<s@s.fr>, relay=mail.s.fr[xx.xx.xx.x]:25, delay=219299, delays=219295/0.04/2.9/0.94, dsn=4.1.8, status=deferred (host mail.s.fr[xx.xx.xx.x] said: 450 4.1.8 <root@pve.xxx.fr>: Sender address rejected: Domain not found (in reply to RCPT TO command))

Je précise que j'auto-héberge mon serveur de messagerie en passant par un relais smtp (mailjet, port 465)

Merci par avance pour votre retour
Sylvain

**Comment by Tontonjo** [comment]
Hello! Merci pour le compliment!
Concernant votre erreur, le domaine semble inexistant -> Domain not found
je pense qu'il vous faut contrôler la configuration DNS de votre domaine.

Passez sur le discord au besoin.

Je clos car cette erreur n'est pas due au script :-)
