### ISSUE TITLE
After running update host I still get the no-subscription message

### ISSUE THREAD

**Issue by dr3am3r-hass** [Tontonjo/proxmox_toolbox#10]
As the the title says the no-subscription message doesn't get removed after running update host. Tried running it a couple of times and also rebooted the server but I still get the no-subscription message.

**Comment by Tontonjo** [comment]
HI!
Try to clear broswer cache / user another browser
THANKS

**Comment by dr3am3r-hass** [comment]
I ctrl + f5 the page and now it works. How simple it can be. Thanks for your help and your awesome script!

**Comment by Tontonjo** [comment]
https://github.com/Tontonjo/proxmox_toolbox/commit/56f0a4d6623fd9ec0417a4424cec8aeb000a97c8
