### ISSUE TITLE
problème : tout accès ssh perdu

### ISSUE THREAD

**Issue by FabriceC01** [Tontonjo/proxmox_toolbox#11]
Bonjour TontonJo,
Merci pour ton travail que je suis depuis quelques mois.
Je viens de mettre à jour mon PM en V7 sans soucis grâce à ton tuto et je viens aussi d'utiliser ton toolbox.
Par contre je viens de  faire une bêtise avec que je ne comprends pas et je ne m'en sors plus.
J'avais déjà un compte root sans autorisation en ssh et un compte que j'appelerai ici perso@pam autorisé en ssh.
j'ai lancé l'option 4) security pour activer fail2ban et j'ai dû ensuite faire une erreur dans les réponses suivantes (je ne voulais pas créer d'autres comptes) car je n'ai plus d'accès ssh avec mon compte "perso" (ni root bien sûr).
je peux toujours me connecter à la GUI (en root et en perso) et à l'intérieur à la console >_shell de proxmox pour rentrer des commandes.
ça fait 4h que je cherche sur internet comment réautoriser mon compte perso@pam en ssh et je n'y arrive pas. Pourrais-tu m'aider ?
Merci d'avance.
Fabrice

**Comment by Tontonjo** [comment]
Hello et merci :-)
Il ne s'agit sans doutes pas d'un bug de la toolbox :-)
Je clos le bug mais le rouvrirais si il s'avère que la toolbox est en cause!

Peux-tu passer sur discord afin que l'on t'aide à résoudre ce problème?
https://discord.com/invite/h6UcpwfGuJ
