### ISSUE TITLE
Restoration of a backup makes system unuseable

### ISSUE THREAD

**Issue by sielnet** [Tontonjo/proxmox_toolbox#15]
we had multiple crashed services after backup restoration.

We did a reinstallation and wont use the backup feature again.
Just wanted to let you know that it is currently unusable.

**Comment by Tontonjo** [comment]
> we had multiple crashed services after backup restoration.
> 
> We did a reinstallation and wont use the backup feature again. Just wanted to let you know that it is currently unusable.

Hi!

I've never heard of restoration causing services crashes, and i know it was used many times.

Do you have any useful information that may help to understand your problem?
Especially, context of  Restoration, logs, version, cluster status and so on?

Closing as it's not a proven toolbox problem atm.

Regards
