### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jpatje** [Tontonjo/proxmox_toolbox#16]
“If you reveive this, it means your email configurations looks correct. Yay!”

reveive -> receive

It's a minor thing but couldn't help to notice. Love your work with this tool. It was so easy to set up email notifications :)

**Comment by Tontonjo** [comment]
Thanks for letting me know, glad it helped you :)

https://github.com/Tontonjo/proxmox_toolbox/commit/dc479495527ea0e69eb5a3376545d786257ac52f
