### ISSUE TITLE
Backup Config via Argument

### ISSUE THREAD

**Issue by mac-linux-free** [Tontonjo/proxmox_toolbox#17]
Hello,

what argument do I have to use to Backup Configuration?

Thank you,

**Comment by Tontonjo** [comment]
> Hello,
> 
> what argument do I have to use to Backup Configuration?
> 
> Thank you,

Hi, absolutely none :)

Were you expecting something special?

**Comment by mac-linux-free** [comment]
Oh...I want to put a config-backup to crontab. So I think I need an argument like proxmox_toolbox.sh -b

**Comment by Tontonjo** [comment]
> Oh...I want to put a config-backup to crontab. So I think I need an argument like proxmox_toolbox.sh -b

i can do that.

**Comment by Tontonjo** [comment]
> Oh...I want to put a config-backup to crontab. So I think I need an argument like proxmox_toolbox.sh -b

Done in: https://github.com/Tontonjo/proxmox_toolbox/commit/d72a3c4c34c77218efd26c4f688ee1e64b118db5

**Comment by mac-linux-free** [comment]
Hello again, sorry to open this up.
Could you add an argument to define the backup-versions like proxmox_toolbox -b -v 10 ?
I want to cron this and rsync away from host.

Thank you.

**Comment by Tontonjo** [comment]
> Hello again, sorry to open this up. Could you add an argument to define the backup-versions like proxmox_toolbox -b -v 10 ? I want to cron this and rsync away from host.
> 
> Thank you.

Hey!

What do you mean by "backup version"  and why is it related to cron and rsync?

The backup already has a timestamp in the name and if you're worried about taking away the latest version i feel it can be very easilly achived with your rsync script.

**Comment by mac-linux-free** [comment]
If I run it daily on 5 cluster nodes, the directory would grow, and I need only the last 10 versions per node.

**Comment by Tontonjo** [comment]
> If I run it daily on 5 cluster nodes, the directory would grow, and I need only the last 10 versions per node.

Just script a purge in that folder along the execution of the backup :)
