### ISSUE TITLE
Restore one cluster node

### ISSUE THREAD

**Issue by mac-linux-free** [Tontonjo/proxmox_toolbox#19]
Hello, due to the grub/zfs non efi bug encountered now with pm 8.1 upgrade I have to reinstall one node after the other.
Does the restore process work on a member node?

Thank you.

**Comment by Tontonjo** [comment]
Hello!

As said in the readme, this has not been tested in a cluster configuration.
As far as i know, it should work on the host, but i'm not sure how the cluster may react.

Please let me know how it goes if you try, very interested!

Regards

**Comment by mac-linux-free** [comment]
Hello!

I got it working. But please could you add one more thing to the backup?

/etc/corosync/authkey it is a file.

It did not work at first. But after copying this file my cluster is up again.

Horray.

**Comment by mac-linux-free** [comment]
but the ssh_keys are messed up

**Comment by mac-linux-free** [comment]
and you have to be sure, that replication jobs are removed at first.

**Comment by Tontonjo** [comment]
> Hello!
> 
> I got it working. But please could you add one more thing to the backup?
> 
> /etc/corosync/authkey it is a file.
> 
> It did not work at first. But after copying this file my cluster is up again.
> 
> Horray.

Will do, thanks you very much for your test and feedback!

**Comment by Tontonjo** [comment]
> but the ssh_keys are messed up

How so?
Is there something we can do about it? Prevent any unwanted behaviors

**Comment by Tontonjo** [comment]
> and you have to be sure, that replication jobs are removed at first.

Ye makes sense, that's the kind of things i was exepecting when i say " i'm not sure how the cluster may react" :)

So in cluster configurations, you have to stop the replication in cluster before restoring the memeber configuration right?

**Comment by mac-linux-free** [comment]
In the next hour I'll do the next node. So thank you.

**Comment by Tontonjo** [comment]
> In the next hour I'll do the next node. So thank you.

https://github.com/Tontonjo/proxmox_toolbox/commit/5ed95f9d5910e1c003ebd9bd0ff0f382f780dfcc

**Comment by mac-linux-free** [comment]
ok it worked
