### ISSUE TITLE
valeur de swappiness perdue au reboot de proxmox

### ISSUE THREAD

**Issue by pamart** [Tontonjo/proxmox_toolbox#2]
Hello,
Pour commencer, un immense merci pour ton script qui facilite bien la vie.
J’ai constaté un petit problème, lorsque l’on change la valeur de swappiness à zéro par exemple, c’est effectif tant que proxmox ne redémarre pas. Après un reboot, la valeur revient à celle par défaut: 60.
J’ai testé ça sur plusieurs hosts avec la dernière version à ce jour de Proxmox, la 7.0.-13

**Comment by Tontonjo** [comment]
Hello!

Ravi de savoir que ce petit tool est utilisé :-) !

En effet je parviens à reproduire ce comportement.
Je ne sais plus si j'avais testé le reboot lors de mes tests (ce qui permettrait de savoir si le soucis est nouveau ou que ça n'a jamais fonctionné)

J'ai fait de rapides tests et recherches sans succès pour le moment.
Je garde ça en tête et si tu parviens de ton côté à trouver la cause et / ou la solution, je suis preneur!
Je vais également voir avec le serveur Discord si par hasard quelqu'un saurait expliquer / résoudre cela.

EDIT: le discord sait tout:
[source](https://www.howtoforge.com/tutorial/linux-swappiness/)
This change has an immediate effect on your system's operation and thus no rebooting is required. In fact, rebooting will revert the swappiness back to its default value (60).

Je vais faire un pr rapidement.

Merci d'avoir relevé ce soucis!

**Comment by Tontonjo** [comment]
Testé (cette fois) et fermé.

https://github.com/Tontonjo/proxmox_toolbox/commit/c73e8a37c6a6ba43acc357f450a5f54f07af1fb0#diff-e19f65901bc5cb24d088a51bdb8e2d398aecd29f3a5d9f986c310994f8776b4d
