### ISSUE TITLE
PBS - Send mail error

### ISSUE THREAD

**Issue by Loic691** [Tontonjo/proxmox_toolbox#3]
Bonjour Tonton Jo
Voici le log d'erreur suite utilisation du toolbox sur un PBS lors d'un test d'envoi.
PBE fraichement installé et mis à jour avec ta toolbox en 2.0.12

```
- What is the recipient email address? :
XXXXXX@gmail.com
- An email will be sent to: XXXXX@gmail.com
proxmox_toolbox/proxmox_toolbox.sh: line 554: mail: command not found
- Email should have been sent - If none received, you may want to check for errors in menu 3
```

Je n'ai aucune erreur dans le menu 3 

`- Checking for known errors that may be found in logs
- No configured error found - nothing to do!

`

**Comment by Tontonjo** [comment]
Hello!
J'imagine que tu parles de PBS?
En effet PBS ne possède pas nativement la librarie pour envoyer des emails.

Pour quelles raisons cherches-tu a configurer les emails dessus?

**Comment by Loic691** [comment]
Oui PBS.
Pour avoir les notifications de PBS au cas ou.
Pour les taches de vérifications notament.

**Comment by Tontonjo** [comment]
Pour les notifications systèmes donc, car a ma connaissance y'a pas de settings pour des tâches ou je me trompe?
Je vois quelques solutions possibles:
- Ajout d'un contrôle de présence de la lib dans le script et installation si absente (mais si il faut d'autres choses je n'en sais rien)
- Je fais en sorte que le script mette un message que PBS ne supporte pas nativement la chose.

Peux-tu tester si l'installation de "apt-get install mailutils" suffit? En validant que les messages systèmes fonctionnent?

**Comment by Loic691** [comment]
Merci pour le retour
Oui ça fonctionne bien. Mail reçu.
En revanche l'objet du mail est le même que sur PVE
`Proxmox server test mail`

EDIT : 
Question complémentaire : Est ce que le backup conf de la toolbox backup bien la conf de messagerie sur PVE et PBS ?

**Comment by Tontonjo** [comment]
Merci pour le test:
Bon l'objet qui est identique c'est pas très important, mais j'ai peut-être une idée.
Pour PBS ce n'est pas le cas car cela ne fait pas partie des configurations de bases, mais on peut facilement corriger cela.£
EDIT: c'était deja le cas - j'avais mal relu les dossiers.

**Comment by Loic691** [comment]
OK merci
Sinon une petite idée d'amélioration également.
Avoir la possibilité d'envoyer les mails des rapports que en cas d'erreur.
Et en bonus tout de même envoyer un mail systématique périodiquement 1 fois par mois par exemple (pour prise de conscience d'une notification messagerie qui cesserai de fonctionner)

**Comment by Tontonjo** [comment]
> OK merci Sinon une petite idée d'amélioration également. Avoir la possibilité d'envoyer les mails des rapports que en cas d'erreur. Et en bonus tout de même envoyer un mail systématique périodiquement 1 fois par mois par exemple (pour prise de conscience d'une notification messagerie qui cesserai de fonctionner)

C'est une bonne idée et c'est bien entendu faisable, mais je ne crois pas que ce soit pertinant car il s'agit selon moi de configurations trop "individuelles" dans le sens ou prendre en compte toutes les possibilités est trop fastidieux.
Si tu as besoin de monitoring, utilise un utilitaire de monitoring.
La toolbox a pour but de faire des configurations "basiques".

Pour les rapport d'erreur de backups, proxmox le fait déjà.

**Comment by Tontonjo** [comment]
> Merci pour le retour Oui ça fonctionne bien. Mail reçu. En revanche l'objet du mail est le même que sur PVE `Proxmox server test mail`
> 
> EDIT : Question complémentaire : Est ce que le backup conf de la toolbox backup bien la conf de messagerie sur PVE et PBS ?
Voila c'est corrigé et amélioré:
- mailutils s'installe si manquant
- nom d'hote et date dans le mail de test

**Comment by Loic691** [comment]
> Pour les rapport d'erreur de backups, proxmox le fait déjà.

Oui je n'avais pas vu => `On failure only`

merci pour tout

**Comment by Tontonjo** [comment]
> > Pour les rapport d'erreur de backups, proxmox le fait déjà.
> 
> Oui je n'avais pas vu => `On failure only`
> 
> merci pour tout

Avec plaisir!
Merci pour avoir signalé ces quelques soucis!
