### ISSUE TITLE
Send mail IPv4 - IPv6

### ISSUE THREAD

**Issue by Loic691** [Tontonjo/proxmox_toolbox#4]
Rebonjour
Suite à l'erreur (voir autre issue) sur PBE, je teste sur PVE.
Voici l'erreur que j'ai et que j'ai du mal à interpreter.
Je n'ai pas d'IPv6 configfuré sur mon serveur PVE (juste une IPv4 fixe locale)
IPv6 est tout de même activé sur mon réseau. PBE semble en ipv6 juste avoir son IP de loopback en fe80

`- Checking for known errors that may be found in logs
Nov  4 09:35:15 pve postfix/smtp[209517]: connect to mail.infomaniak.com[2001:1600:0:aaaa::1:2]:465: Network is unreachable
Nov  4 09:36:10 pve postfix/smtp[209792]: connect to mail.infomaniak.com[2001:1600:0:aaaa::1:1]:465: Network is unreachable
Nov  4 09:36:10 pve postfix/smtp[209792]: connect to mail.infomaniak.com[2001:1600:0:aaaa::1:2]:465: Network is unreachable
- Are you on IPv4 AND your host can resolve and access public adresses? y = yes / anything = no: ^C
`

Comment puis-je en arriver là ?
J'ai indiqué yes dans la question mais cela ne semble pas améliorer la situation.
Pas sur que ça soit une issue rééelle, plutôt conf, mais dans le doute je poste quand même

EDIT : 
Et la config du postfix généré par le script

`myhostname=XXXXX.XXXXXXXx

smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = $myhostname, localhost.$mydomain, localhost
relayhost =[mail.infomaniak.com]:465
mynetworks = 127.0.0.0/8
inet_interfaces = loopback-only
recipient_delimiter = +

compatibility_level = 2

smtp_use_tls = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_sasl_security_options = noanonymous
smtp_sasl_auth_enable = yes
sender_canonical_maps = hash:/etc/postfix/canonical
inet_protocols = ipv4
`

**Comment by Tontonjo** [comment]
Hello!
Alors c'est un peu cryptique en effet mais ce que cela veut dire c'est que:
- le serveur de infomaniak est résolu par une adresse IPV6 et que postfix ne parviens pas à le joindre.

Donc la question est:
Si ton réseau est en IPV6, cette erreur peut indiquer une mauvaise config réseau
Si il ne l'est pas, il ne devrait pas résoudre par cette adresse, c'est pour cela que je demande si la résolution (configuration DNS) est bien juste.

A mon avis, si tu ne sais pas, tu peux faire oui pour tenter de résoudre.
EDIT: je viens de voir la précision concernant la réponse à la tentative de correction: Possible de passer sur discord?

**Comment by Tontonjo** [comment]
Ceci n'étant pas un bug du script à proprement parler, je me permets de fermer ce cas.
En cas de besoins, passe sur le serveur Discord!
