### ISSUE TITLE
Option PVE & PBS on one server for backup

### ISSUE THREAD

**Issue by mac-linux-free** [Tontonjo/proxmox_toolbox#5]
Hello,

thank you so much for this great script.

Could you please add an backup-and-restore option where PBS and PVE is installed on one server.

That would be great.
Thx

**Comment by Tontonjo** [comment]
Hello!
Thanks for your message.

This make me think about how useless it may be to have 2 task and guess we could merge them.
Did not tested at all :

here are the folder that were not backuped initially under pbs that will now be:
/etc/pve/ /etc/lvm/ /etc/modprobe.d/ /var/lib/pve-firewall/ /var/lib/pve-cluster/  /etc/vzdump.conf /etc/ksmtuned.conf


please try:
https://github.com/Tontonjo/proxmox_toolbox/tree/pve_pbs_backup_merge

Please test and give me a feedback.

**Comment by mac-linux-free** [comment]
works as expected...thx again...did not try a restore yet.

**Comment by Tontonjo** [comment]
Will merge once tested a bit
