### ISSUE TITLE
[FEATURE SUGGESTION] Additional Packages

### ISSUE THREAD

**Issue by BadCo-NZ** [Tontonjo/proxmox_toolbox#7]
Hi, I recently setup a second node and came across a few things that might be useful to add to the Toolbox

Second up, is additional packages.

* ``lshw`` for identifying hardware
* ``lm-sensors`` for additional sensor information for fan control scripts etc
* ``corosync-qdevice`` needed for having a third 'qdevice' node in even numbered clusters. Often a SBC.

I'll add others as I think of them.

**Comment by Tontonjo** [comment]
Hi!

Thanks for your suggestions.
I'll take a look on that, the lshw and lm-sensors sounfs good, but i think i wont add packages related to features that may not be installed -> corosync

**Comment by BadCo-NZ** [comment]
Hi @Tontonjo, that all sounds fair to me :)

**Comment by docop** [comment]
Hi  so if we do install other package and like here lm-sensor.. So the backup will not be made and only result in error after ?  Can it be an option to do a full backup with all package installed and setting ?  Or basically, just an acronis image of the pve partition will be enought or better ?
thanks

**Comment by Tontonjo** [comment]
> Hi so if we do install other package and like here lm-sensor.. So the backup will not be made and only result in error after ? Can it be an option to do a full backup with all package installed and setting ? Or basically, just an acronis image of the pve partition will be enought or better ? thanks

Please have a look at the readme :-)

**Comment by AlessioRosi** [comment]
What about to add a script to install and configure OpenVPN for syncing localPBS to a  remote PBS.
This could be a really amazing feature!

**Comment by Tontonjo** [comment]
> 

Hello and thanks for your request!

I dont think i will implement this in the toolbox for different reasons:
- This is not a "basic" configuration that everybody may need
- This will only help people using OpenVPN - what about the other clients?

On my side, i use NAT to access my localPBS to a remote PBS whith a firewall rule to allow only my IP to access.

**Comment by Tontonjo** [comment]
> What about to add a script to install and configure OpenVPN for syncing localPBS to a remote PBS. This could be a really amazing feature!

Hello and thanks for your request!

I dont think i will implement this in the toolbox for different reasons:

This is not a "basic" configuration that everybody may need
This will only help people using OpenVPN - what about the other clients?
On my side, i use NAT to access my localPBS to a remote PBS whith a firewall rule to allow only my IP to access.

**Comment by AlessioRosi** [comment]
> > What about to add a script to install and configure OpenVPN for syncing localPBS to a remote PBS. This could be a really amazing feature!
> 
> Hello and thanks for your request!
> 
> I dont think i will implement this in the toolbox for different reasons:
> 
> This is not a "basic" configuration that everybody may need This will only help people using OpenVPN - what about the other clients? On my side, i use NAT to access my localPBS to a remote PBS whith a firewall rule to allow only my IP to access.

Yes, I agree with you!
I'm thinking not only at OpenVPN, but in general VPNs. 
My suggestion is only for security reasons. In this moment i'm working exactly as you described.

In any case, thank you for your toolbox!👌
