### ISSUE TITLE
[FEATURE SUGGESTION] Enable IOMMU

### ISSUE THREAD

**Issue by BadCo-NZ** [Tontonjo/proxmox_toolbox#9]
Hi, I recently setup a second node and came across a few things that might be useful to add to the Toolbox

Third up, is enabling IOMMU. This differs for BIOS (Grub) and UEFI (systemd-boot).

## Enable IOMMU For BIOS/GRUB

Reference: 
https://pve.proxmox.com/wiki/PCI(e)_Passthrough

Follow the linked instructions.

For the kernel command line, add:

```
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} intel_iommu=on"
```

To a new file:

```
nano /etc/default/grub.d/iommu.cfg
```

Save, exit, and update grub

```
update-grub
```

## Enable IOMMU For UEFI/Systemd-boot

Reference: 
https://pve.proxmox.com/wiki/Host_Bootloader#sysboot_edit_kernel_cmdline
https://matthewdeporter.com/proxmox/proxmox-pci-passthrough/#iommu-systemd-boot

Add the ''intel_iommu=on'' ''iommu=pt'' settings to the Systemd-boot command line.

Edit the /etc/kernel/cmdline:

```
nano /etc/kernel/cmdline
```

Before modification:
```
root=ZFS=rpool/ROOT/pve-1 boot=zfs
```

After:
```
root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on iommu=pt
```

Update the Systemd-boot scripts:
```
pve-efiboot-tool refresh
```

Verify loaded kernel cmdline:
```
$ cat /proc/cmdline
initrd=\EFI\proxmox\5.4.73-1-pve\initrd.img-5.4.73-1-pve root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on iommu=pt
```

Verify that IOMMU is enabled and Virtualization Technology for Directed I/O:
<code>
$ dmesg | grep -e DMAR -e IOMMU -e AMD-Vi
[    0.013784] ACPI: DMAR 0x000000007E2CAB18 000130 (v01 A M I  OEMDMAR  00000001 INTL 00000001)
[    0.155343] DMAR: IOMMU enabled

...

[    1.474961] DMAR: Intel(R) Virtualization Technology for Directed I/O
</code>

**Comment by Tontonjo** [comment]
Thanks for your suggestion

As this is a "low level" change on a non-directly Proxmox related stuff, i'm feeling it's better that people who need this feature learn how it works as it may lead to too many problems and requests about it.

+ we need to take accountance about both AMD and Intel platforms, wiche is a complication

**Comment by BadCo-NZ** [comment]
Hi @Tontonjo, I would say that enabling IOMMU is essential for a new PVE install. You can't do LXCs and VMs without IOMMU which would make it a crappy hypervisor haha.

Allow for Intel and AMD would in theory be as simple as prompting the user, or have two different menu options, or even maybe checking the hardware processor class?

**Comment by Tontonjo** [comment]
I never had to enable this in order to have VM or containers to run correctly.
If you feel this is needed, please make a PR :-)

**Comment by BadCo-NZ** [comment]
Sorry I got mixed up, it is for PCIe passthrough in VMs and not for running LXCs and VMs themselves.

For example, passing a GPU through to a desktop guest or passing a HBA through to TrueNAS guest.

**Comment by Tontonjo** [comment]
I guessed so, but my first was wrote with this in mind aswell.

**Comment by gdragon-git** [comment]
Just want to add that being able to turn on IOMMU is a must have for my use case. Without it, I can't access the PCI sata controller that I use for managing disks via Proxmox for a TrueNAS VM on the system.

**Comment by Tontonjo** [comment]
> Just want to add that being able to turn on IOMMU is a must have for my use case. Without it, I can't access the PCI sata controller that I use for managing disks via Proxmox for a TrueNAS VM on the system.

Hello!

When entering a conversation, especially to ask for something, you may want to say hello and give a thanks :)

To answer your request:
I dont plan at the moment to implement this as i think this is something that need to be well understood by the user, thus it needs to be hand deployed to be well setted-up.

Out of topic:
On my side, i would not suggest to passtrough PCI controllers and i would not virtualise TrueNAS, especially because you need to passtrough a whole controller to it in order to have something reliable with ZFS.

**Comment by BadCo-NZ** [comment]
> Out of topic: On my side, i would not suggest to passtrough PCI controllers and i would not virtualise TrueNAS, especially because you need to passtrough a whole controller to it in order to have something reliable with ZFS.

Hey @Tontonjo! OP Here, coincidentally the reason I needed IOMMU is for passing through HBA to TrueNAS Core VM 😅

While it is not supported or recommended, it is completely feasible, you can even add qemu-guest-agent to get more control.

Oh, I also pass a GPU through to a Manjaro VM for game streaming to my TV.

Other people may use GPUs for transcoding in Plex/Jellyfin or Google Coral for detection in Frigate

Any who, adding IOMMU to your script was just a suggestion and I appreciate you wanting to stick to an opinionated script without overdoing it with bloat.

Thanks!

**Comment by Tontonjo** [comment]
> > Out of topic: On my side, i would not suggest to passtrough PCI controllers and i would not virtualise TrueNAS, especially because you need to passtrough a whole controller to it in order to have something reliable with ZFS.
> 
> Hey @Tontonjo! OP Here, coincidentally the reason I needed IOMMU is for passing through HBA to TrueNAS Core VM 😅
> 
> While it is not supported or recommended, it is completely feasible, you can even add qemu-guest-agent to get more control.
> 
> Oh, I also pass a GPU through to a Manjaro VM for game streaming to my TV.
> 
> Other people may use GPUs for transcoding in Plex/Jellyfin or Google Coral for detection in Frigate
> 
> Any who, adding IOMMU to your script was just a suggestion and I appreciate you wanting to stick to an opinionated script without overdoing it with bloat.
> 
> Thanks!

Hey OP @BadCo-NZ  :)
Yeah i do know it feasible and it was indeed not my point 💯 

Why are you guys virtualizing Truenas instead of running it on bare-metal?
I do also passtrough a gpu a VM for some jellyfin streaming.

On the discord server where i use to help some other users, i encountered a lot of people having trouble implementing passtrough with success, sometimes even tough their hardware was looking to be supporting it with fines IOMMU groups and so on and i really feel people need to understand how it works. it's not just some "small configurations".

I'm thinking about adding a new option with some "advanced configurations" but in order to enable IOMMU, i thing theres a lots of "checks" to do before. It's not just about applying configurations.

**Comment by gdragon-git** [comment]
Sorry. Did not mean to be rude. Was just adding in my vote and explaining my use case. Thank you for your project and good luck where you take it.
